### ISSUE TITLE
"Что за аниме?"

### ISSUE THREAD

**Issue by MordorDie** [Jumas-Cola/callback_vk_bot#1]
Это больше реквест, что хотелось бы видеть)
Хотелось бы, чтобы бот на слова "Что за аниме" и прикрепленную к этой фразе скрину выдавал название аниме.

Тут более подробно так сказать: https://soruly.github.io/whatanime.ga .

**Comment by soruly** [comment]
whatanime.ga has moved to https://trace.moe
https://www.patreon.com/posts/moving-to-new-22212117
